import React from 'react';

const HikePrintView = ({ hike, attendees = [] }) => {
  return (
    <div className="print-view" style={{ padding: '20px', fontFamily: 'Arial, sans-serif' }}>
      <style>
        {`
          @media print {
            body * {
              visibility: hidden;
            }
            .print-view, .print-view * {
              visibility: visible;
            }
            .print-view {
              position: absolute;
              left: 0;
              top: 0;
              width: 100%;
            }
            .no-print {
              display: none !important;
            }
          }
        `}
      </style>

      <div style={{ textAlign: 'center', marginBottom: '30px', borderBottom: '2px solid #000', paddingBottom: '20px' }}>
        <h1 style={{ margin: '0 0 10px 0' }}>{hike.name}</h1>
        <h3 style={{ margin: '0', color: '#666' }}>The Narrow Trail Hiking Group</h3>
      </div>

      <div style={{ marginBottom: '20px' }}>
        <h2 style={{ borderBottom: '1px solid #ccc', paddingBottom: '5px' }}>Hike Details</h2>
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <tbody>
            <tr>
              <td style={{ padding: '8px', fontWeight: 'bold', width: '150px' }}>Date:</td>
              <td style={{ padding: '8px' }}>{new Date(hike.date).toLocaleDateString()}</td>
            </tr>
            <tr>
              <td style={{ padding: '8px', fontWeight: 'bold' }}>Difficulty:</td>
              <td style={{ padding: '8px' }}>{hike.difficulty}</td>
            </tr>
            <tr>
              <td style={{ padding: '8px', fontWeight: 'bold' }}>Distance:</td>
              <td style={{ padding: '8px' }}>{hike.distance}</td>
            </tr>
            <tr>
              <td style={{ padding: '8px', fontWeight: 'bold' }}>Type:</td>
              <td style={{ padding: '8px' }}>{hike.type === 'day' ? 'Day Hike' : 'Multi-Day'}</td>
            </tr>
            <tr>
              <td style={{ padding: '8px', fontWeight: 'bold' }}>Group:</td>
              <td style={{ padding: '8px' }}>{hike.group_type === 'family' ? 'Family' : "Men's"}</td>
            </tr>
            {hike.cost > 0 && (
              <tr>
                <td style={{ padding: '8px', fontWeight: 'bold' }}>Cost:</td>
                <td style={{ padding: '8px' }}>R{hike.cost}</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {hike.description && (
        <div style={{ marginBottom: '20px' }}>
          <h2 style={{ borderBottom: '1px solid #ccc', paddingBottom: '5px' }}>Description</h2>
          <p>{hike.description}</p>
        </div>
      )}

      {hike.type === 'multi' && hike.daily_distances && hike.daily_distances.length > 0 && (
        <div style={{ marginBottom: '20px' }}>
          <h2 style={{ borderBottom: '1px solid #ccc', paddingBottom: '5px' }}>Daily Distances</h2>
          <ul>
            {hike.daily_distances.map((distance, idx) => (
              <li key={idx}>Day {idx + 1}: {distance}</li>
            ))}
          </ul>
        </div>
      )}

      {hike.overnight_facilities && (
        <div style={{ marginBottom: '20px' }}>
          <h2 style={{ borderBottom: '1px solid #ccc', paddingBottom: '5px' }}>Overnight Facilities</h2>
          <p>{hike.overnight_facilities}</p>
        </div>
      )}

      {attendees.length > 0 && (
        <div style={{ marginBottom: '20px' }}>
          <h2 style={{ borderBottom: '1px solid #ccc', paddingBottom: '5px' }}>Confirmed Attendees ({attendees.length})</h2>
          <ul>
            {attendees.map((attendee, idx) => (
              <li key={idx}>{attendee.name} - {attendee.phone}</li>
            ))}
          </ul>
        </div>
      )}

      <div style={{ marginTop: '40px', pageBreakBefore: 'avoid' }}>
        <h2 style={{ borderBottom: '1px solid #ccc', paddingBottom: '5px' }}>Packing List</h2>
        <div style={{ columnCount: 2, columnGap: '20px' }}>
          <p style={{ margin: '5px 0' }}>Water (2-3L)</p>
          <p style={{ margin: '5px 0' }}>Snacks / Trail mix</p>
          <p style={{ margin: '5px 0' }}>Lunch</p>
          <p style={{ margin: '5px 0' }}>Sun protection (hat, sunscreen)</p>
          <p style={{ margin: '5px 0' }}>First aid kit</p>
          <p style={{ margin: '5px 0' }}>Comfortable hiking boots</p>
          <p style={{ margin: '5px 0' }}>Rain jacket</p>
          <p style={{ margin: '5px 0' }}>Warm layer</p>
          <p style={{ margin: '5px 0' }}>Headlamp / Torch</p>
          <p style={{ margin: '5px 0' }}>Phone & power bank</p>
        </div>
      </div>

      <div style={{ marginTop: '40px', textAlign: 'center', fontSize: '12px', color: '#666' }}>
        <p>Generated by The Narrow Trail Hiking Portal</p>
        <p>"Small is the gate and narrow the road that leads to life" - Matthew 7:14</p>
      </div>
    </div>
  );
};

export default HikePrintView;
