# Home Assistant Development Configuration
# This configuration is optimized for testing integrations

# Basic configuration
default_config:

# Enable debug logging for our integration
logger:
  default: info
  logs:
    custom_components.hiking_portal: debug
    custom_components.hiking_portal_v2: debug
    homeassistant.config_entries: debug
    homeassistant.loader: debug

# Enable development mode
homeassistant:
  # Set location for testing
  name: "HA Dev Environment"
  latitude: 51.5074
  longitude: -0.1278
  elevation: 11
  unit_system: metric
  time_zone: "Europe/London"
  
  # Development settings
  auth_mfa_modules:
    - type: totp
  
  # Allow unsafe loading for development
  allowlist_external_dirs:
    - /config/custom_components

# Enable frontend for easy testing
frontend:
  themes: !include_dir_merge_named themes

# Enable configuration UI
config:

# Enable mobile app support for testing
mobile_app:

# Enable system health
system_health:

# Enable energy dashboard
energy:

# Enable logbook
logbook:

# Enable history
history:

# Enable recorder with PostgreSQL (optional)
# Uncomment if you want to use the PostgreSQL container
# recorder:
#   db_url: postgresql://homeassistant:homeassistant_dev_password@localhost:5432/homeassistant

# Enable simple HTTP server for testing
http:
  server_port: 8123
  # Uncomment for external access (not recommended for production)
  # server_host: 0.0.0.0
  # trusted_networks:
  #   - 192.168.1.0/24
  #   - 127.0.0.1

# Development automation for testing
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Sample sensors for testing
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'time_date'
      - 'time_utc'
      - 'beat'
  
  # Template sensor for testing
  - platform: template
    sensors:
      dev_environment:
        friendly_name: "Development Environment"
        value_template: "Active"
        icon_template: mdi:test-tube