express_interest:
  name: Express Interest in Hike
  description: Express interest in joining a hike
  fields:
    hike_id:
      name: Hike ID
      description: The ID of the hike to join
      required: true
      example: 123
      selector:
        number:
          min: 1
          mode: box

remove_interest:
  name: Remove Interest from Hike
  description: Remove your interest from a hike
  fields:
    hike_id:
      name: Hike ID
      description: The ID of the hike to leave
      required: true
      example: 123
      selector:
        number:
          min: 1
          mode: box

mark_attendance:
  name: Mark Attendance
  description: Mark your attendance for a hike
  fields:
    hike_id:
      name: Hike ID
      description: The ID of the hike
      required: true
      example: 123
      selector:
        number:
          min: 1
          mode: box
    status:
      name: Status
      description: Attendance status
      required: true
      default: "present"
      example: "present"
      selector:
        select:
          options:
            - "present"
            - "absent"
            - "maybe"

send_notification:
  name: Send Notification
  description: Send a notification to hike participants
  fields:
    hike_id:
      name: Hike ID
      description: The ID of the hike
      required: true
      example: 123
      selector:
        number:
          min: 1
          mode: box
    message:
      name: Message
      description: The notification message to send
      required: true
      example: "Don't forget to bring water!"
      selector:
        text:
          multiline: true

mark_notification_read:
  name: Mark Notification Read
  description: Mark a notification as read
  fields:
    notification_id:
      name: Notification ID
      description: The ID of the notification to mark as read
      required: true
      example: 456
      selector:
        number:
          min: 1
          mode: box

record_payment:
  name: Record Payment
  description: Record a payment for a hike
  fields:
    hike_id:
      name: Hike ID
      description: The ID of the hike
      required: true
      example: 123
      selector:
        number:
          min: 1
          mode: box
    user_id:
      name: User ID
      description: The ID of the user making the payment
      required: true
      example: 789
      selector:
        number:
          min: 1
          mode: box
    amount:
      name: Amount
      description: Payment amount in ZAR
      required: true
      example: 250.00
      selector:
        number:
          min: 0
          step: 0.01
          mode: box
    payment_method:
      name: Payment Method
      description: Method of payment
      required: false
      default: "cash"
      example: "cash"
      selector:
        select:
          options:
            - "cash"
            - "eft"
            - "card"
            - "other"

get_weather:
  name: Get Weather
  description: Get weather forecast for a hike
  fields:
    hike_id:
      name: Hike ID
      description: The ID of the hike
      required: true
      example: 123
      selector:
        number:
          min: 1
          mode: box
